### ISSUE TITLE
Document in README that you can select the port on which sparREST is listening

### ISSUE THREAD

**Issue by dfreniche** [kasappeal/sparrest#4]
If you do:

```
$ python server.py 10000
```

sparREST listens on port 10000. This opens the door to having more than one sparREST server on the same machine. But it's not mentioned on the README file.

**Comment by kasappeal** [comment]
Fixed in https://github.com/kasappeal/sparrest/commit/648882e962618ecc21e4bd27b393ac90d5a9fddb
